# NTP (Network Time Protocol) Service Configuration File

# Originally created by ntp-4.2.8p18a2-win32-setup.exe.
# PLEASE CHECK THIS FILE CAREFULLY AND MODIFY IT IF REQUIRED.
# For additional documentation and background information, see:
# https://www.ntp.org/documentation/4.2.8-series/

# **** ATTENTION ****:
# You have to restart the NTP service after modifying this file
# to activate the changes.

# The following restrict statements are intended for secure operation.
# By default, access to services other than getting the time via NTP protocol
# is only allowed from localhost, so strict default restrictions apply.

# Basic default restrictions.
restrict default notrap nomodify nopeer noepeer noquery

# Allow full access from localhost.
restrict 127.0.0.1
restrict ::1  # Comment out if IPv6 is not supported.

# To allow access from specific hosts, add lines like this:
# restrict <IP ADDRESS OF REMOTE HOST> 

# To allow acccess from specific subnets, add lines like this:
# restrict <IP ADDRESS> mask <NETMASK>

# Relaxed restrictions apply to all explicitly configured servers
# and peers, including pool servers.
restrict source notrap nomodify noquery

# Use drift file
driftfile "C:\Program Files (x86)\NTP\etc\ntp.drift"

ntsdumpdir "D:\ntp\ports\winnt\vs2015\x64-out\Debug\ntpdump"
# Your local system clock, could be used as a backup
# (this is only useful if you need to distribute time no matter how good or bad it is)
#server 127.127.1.0
# but it should operate at a high stratum level to let the clients know and force them to
# use any other timesource they may have.
#fudge 127.127.1.0 stratum 12

# Use a NTP server from the ntp pool project (see https://www.pool.ntp.org)
# Please note that you need at least four different servers to be at least protected against
# one falseticker. If you only rely on internet time, it is highly recommended to add
# additional servers here. 
# The 'iburst' keyword speeds up initial synchronization, please check the documentation for more details!
#server time.cloudflare.com iburst nts

server 1.ntp.ubuntu.com iburst nts
server 2.ntp.ubuntu.com iburst nts
server 3.ntp.ubuntu.com iburst nts
server 4.ntp.ubuntu.com iburst nts
server lul1.nts.netnod.se iburst nts
server lul2.nts.netnod.se iburst nts
server mmo1.nts.netnod.se iburst nts
server mmo2.nts.netnod.se iburst nts
server sth1.nts.netnod.se iburst nts
server sth2.nts.netnod.se iburst nts

#server svl1.nts.netnod.se	iburst nts
#server svl2.nts.netnod.se   iburst nts



# End of generated ntp.conf --- Please edit this to suite your needs
