/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2026-03-30 09:41:03 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[214] = {
	/* 0       258             T_Abbrev */	"abbrev",
	/* 1       259                T_Age */	"age",
	/* 2       260                T_All */	"all",
	/* 3       261              T_Allan */	"allan",
	/* 4       262           T_Allpeers */	"allpeers",
	/* 5       263               T_Auth */	"auth",
	/* 6       264            T_Autokey */	"autokey",
	/* 7       265            T_Automax */	"automax",
	/* 8       266            T_Average */	"average",
	/* 9       267           T_Basedate */	"basedate",
	/* 10      268            T_Bclient */	"bclient",
	/* 11      269        T_Bcpollbstep */	"bcpollbstep",
	/* 12      270             T_Beacon */	"beacon",
	/* 13      271          T_Broadcast */	"broadcast",
	/* 14      272    T_Broadcastclient */	"broadcastclient",
	/* 15      273     T_Broadcastdelay */	"broadcastdelay",
	/* 16      274              T_Burst */	"burst",
	/* 17      275          T_Calibrate */	"calibrate",
	/* 18      276            T_Ceiling */	"ceiling",
	/* 19      277          T_Checkhash */	"checkhash",
	/* 20      278         T_Clockstats */	"clockstats",
	/* 21      279             T_Cohort */	"cohort",
	/* 22      280         T_ControlKey */	"controlkey",
	/* 23      281             T_Crypto */	"crypto",
	/* 24      282        T_Cryptostats */	"cryptostats",
	/* 25      283                T_Ctl */	"ctl",
	/* 26      284                T_Day */	"day",
	/* 27      285            T_Default */	"default",
	/* 28      286        T_Delrestrict */	"delrestrict",
	/* 29      287             T_Device */	"device",
	/* 30      288             T_Digest */	"digest",
	/* 31      289            T_Disable */	"disable",
	/* 32      290            T_Discard */	"discard",
	/* 33      291         T_Dispersion */	"dispersion",
	/* 34      292             T_Double */	NULL,
	/* 35      293          T_Driftfile */	"driftfile",
	/* 36      294               T_Drop */	"drop",
	/* 37      295               T_Dscp */	"dscp",
	/* 38      296           T_Ellipsis */	"...",
	/* 39      297             T_Enable */	"enable",
	/* 40      298                T_End */	"end",
	/* 41      299              T_Epeer */	"epeer",
	/* 42      300              T_False */	NULL,
	/* 43      301               T_File */	"file",
	/* 44      302            T_Filegen */	"filegen",
	/* 45      303            T_Filenum */	"filenum",
	/* 46      304              T_Flag1 */	"flag1",
	/* 47      305              T_Flag2 */	"flag2",
	/* 48      306              T_Flag3 */	"flag3",
	/* 49      307              T_Flag4 */	"flag4",
	/* 50      308              T_Flake */	"flake",
	/* 51      309              T_Floor */	"floor",
	/* 52      310               T_Freq */	"freq",
	/* 53      311              T_Fudge */	"fudge",
	/* 54      312               T_Fuzz */	"fuzz",
	/* 55      313               T_Host */	"host",
	/* 56      314           T_Huffpuff */	"huffpuff",
	/* 57      315             T_Iburst */	"iburst",
	/* 58      316              T_Ident */	"ident",
	/* 59      317             T_Ignore */	"ignore",
	/* 60      318         T_Ignorehash */	"ignorehash",
	/* 61      319           T_Incalloc */	"incalloc",
	/* 62      320             T_Incmem */	"incmem",
	/* 63      321          T_Initalloc */	"initalloc",
	/* 64      322            T_Initmem */	"initmem",
	/* 65      323        T_Includefile */	"includefile",
	/* 66      324            T_Integer */	NULL,
	/* 67      325          T_Interface */	"interface",
	/* 68      326           T_Intrange */	NULL,
	/* 69      327                 T_Io */	"io",
	/* 70      328        T_Ippeerlimit */	"ippeerlimit",
	/* 71      329               T_Ipv4 */	"ipv4",
	/* 72      330          T_Ipv4_flag */	"-4",
	/* 73      331               T_Ipv6 */	"ipv6",
	/* 74      332          T_Ipv6_flag */	"-6",
	/* 75      333             T_Kernel */	"kernel",
	/* 76      334                T_Key */	"key",
	/* 77      335               T_Keys */	"keys",
	/* 78      336            T_Keysdir */	"keysdir",
	/* 79      337                T_Kod */	"kod",
	/* 80      338           T_Leapfile */	"leapfile",
	/* 81      339  T_Leapsmearinterval */	"leapsmearinterval",
	/* 82      340            T_Limited */	"limited",
	/* 83      341               T_Link */	"link",
	/* 84      342             T_Listen */	"listen",
	/* 85      343          T_Logconfig */	"logconfig",
	/* 86      344            T_Logfile */	"logfile",
	/* 87      345          T_Loopstats */	"loopstats",
	/* 88      346        T_Lowpriotrap */	"lowpriotrap",
	/* 89      347     T_Manycastclient */	"manycastclient",
	/* 90      348     T_Manycastserver */	"manycastserver",
	/* 91      349               T_Mask */	"mask",
	/* 92      350             T_Maxage */	"maxage",
	/* 93      351           T_Maxclock */	"maxclock",
	/* 94      352           T_Maxdepth */	"maxdepth",
	/* 95      353            T_Maxdist */	"maxdist",
	/* 96      354             T_Maxmem */	"maxmem",
	/* 97      355            T_Maxpoll */	"maxpoll",
	/* 98      356          T_Mdnstries */	"mdnstries",
	/* 99      357                T_Mem */	"mem",
	/* 100     358            T_Memlock */	"memlock",
	/* 101     359           T_Minclock */	"minclock",
	/* 102     360           T_Mindepth */	"mindepth",
	/* 103     361            T_Mindist */	"mindist",
	/* 104     362            T_Minimum */	"minimum",
	/* 105     363          T_Minjitter */	"minjitter",
	/* 106     364            T_Minpoll */	"minpoll",
	/* 107     365            T_Minsane */	"minsane",
	/* 108     366               T_Mode */	"mode",
	/* 109     367              T_Mode7 */	"mode7",
	/* 110     368            T_Monitor */	"monitor",
	/* 111     369              T_Month */	"month",
	/* 112     370                T_Mru */	"mru",
	/* 113     371             T_Mssntp */	"mssntp",
	/* 114     372    T_Multicastclient */	"multicastclient",
	/* 115     373                T_Nic */	"nic",
	/* 116     374             T_Nolink */	"nolink",
	/* 117     375           T_Nomodify */	"nomodify",
	/* 118     376          T_Nomrulist */	"nomrulist",
	/* 119     377               T_None */	"none",
	/* 120     378        T_Nonvolatile */	"nonvolatile",
	/* 121     379            T_Noepeer */	"noepeer",
	/* 122     380             T_Nopeer */	"nopeer",
	/* 123     381            T_Noquery */	"noquery",
	/* 124     382           T_Noselect */	"noselect",
	/* 125     383            T_Noserve */	"noserve",
	/* 126     384             T_Notrap */	"notrap",
	/* 127     385            T_Notrust */	"notrust",
	/* 128     386                T_Ntp */	"ntp",
	/* 129     387            T_Ntpport */	"ntpport",
	/* 130     388     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 131     389             T_Orphan */	"orphan",
	/* 132     390         T_Orphanwait */	"orphanwait",
	/* 133     391          T_PCEdigest */	"peer_clear_digest_early",
	/* 134     392              T_Panic */	"panic",
	/* 135     393               T_Peer */	"peer",
	/* 136     394          T_Peerstats */	"peerstats",
	/* 137     395              T_Phone */	"phone",
	/* 138     396                T_Pid */	"pid",
	/* 139     397            T_Pidfile */	"pidfile",
	/* 140     398               T_Poll */	"poll",
	/* 141     399       T_PollSkewList */	"pollskewlist",
	/* 142     400               T_Pool */	"pool",
	/* 143     401               T_Port */	"port",
	/* 144     402            T_PpsData */	"ppsdata",
	/* 145     403            T_Preempt */	"preempt",
	/* 146     404             T_Prefer */	"prefer",
	/* 147     405         T_Protostats */	"protostats",
	/* 148     406                 T_Pw */	"pw",
	/* 149     407           T_Randfile */	"randfile",
	/* 150     408           T_Rawstats */	"rawstats",
	/* 151     409              T_Refid */	"refid",
	/* 152     410         T_Requestkey */	"requestkey",
	/* 153     411              T_Reset */	"reset",
	/* 154     412           T_Restrict */	"restrict",
	/* 155     413             T_Revoke */	"revoke",
	/* 156     414             T_Rlimit */	"rlimit",
	/* 157     415      T_Saveconfigdir */	"saveconfigdir",
	/* 158     416             T_Server */	"server",
	/* 159     417     T_Serverresponse */	"serverresponse",
	/* 160     418 T_ServerresponseFuzz */	NULL,
	/* 161     419             T_Setvar */	"setvar",
	/* 162     420             T_Source */	"source",
	/* 163     421          T_Stacksize */	"stacksize",
	/* 164     422         T_Statistics */	"statistics",
	/* 165     423              T_Stats */	"stats",
	/* 166     424           T_Statsdir */	"statsdir",
	/* 167     425               T_Step */	"step",
	/* 168     426           T_Stepback */	"stepback",
	/* 169     427            T_Stepfwd */	"stepfwd",
	/* 170     428            T_Stepout */	"stepout",
	/* 171     429            T_Stratum */	"stratum",
	/* 172     430             T_String */	NULL,
	/* 173     431                T_Sys */	"sys",
	/* 174     432           T_Sysstats */	"sysstats",
	/* 175     433               T_Tick */	"tick",
	/* 176     434              T_Time1 */	"time1",
	/* 177     435              T_Time2 */	"time2",
	/* 178     436           T_TimeData */	"timedata",
	/* 179     437              T_Timer */	"timer",
	/* 180     438        T_Timingstats */	"timingstats",
	/* 181     439             T_Tinker */	"tinker",
	/* 182     440                T_Tos */	"tos",
	/* 183     441               T_Trap */	"trap",
	/* 184     442               T_True */	"true",
	/* 185     443         T_Trustedkey */	"trustedkey",
	/* 186     444                T_Ttl */	"ttl",
	/* 187     445               T_Type */	"type",
	/* 188     446              T_U_int */	NULL,
	/* 189     447           T_UEcrypto */	"unpeer_crypto_early",
	/* 190     448        T_UEcryptonak */	"unpeer_crypto_nak_early",
	/* 191     449           T_UEdigest */	"unpeer_digest_early",
	/* 192     450           T_Unconfig */	"unconfig",
	/* 193     451             T_Unpeer */	"unpeer",
	/* 194     452            T_Version */	"version",
	/* 195     453    T_WanderThreshold */	NULL,
	/* 196     454               T_Week */	"week",
	/* 197     455           T_Wildcard */	"wildcard",
	/* 198     456             T_Xleave */	"xleave",
	/* 199     457           T_Xmtnonce */	"xmtnonce",
	/* 200     458               T_Year */	"year",
	/* 201     459               T_Flag */	NULL,
	/* 202     460                T_EOC */	NULL,
	/* 203     461           T_Simulate */	"simulate",
	/* 204     462         T_Beep_Delay */	"beep_delay",
	/* 205     463       T_Sim_Duration */	"simulation_duration",
	/* 206     464      T_Server_Offset */	"server_offset",
	/* 207     465           T_Duration */	"duration",
	/* 208     466        T_Freq_Offset */	"freq_offset",
	/* 209     467             T_Wander */	"wander",
	/* 210     468             T_Jitter */	"jitter",
	/* 211     469         T_Prop_Delay */	"prop_delay",
	/* 212     470         T_Proc_Delay */	"proc_delay",
	/* 213     471                T_Nts */	"nts"
};

#define SCANNER_INIT_S 1009

const scan_state sst[1012] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      332,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      296,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       23,     2 ), /*     4                   */
  S_ST( 'b',	3,        6,     0 ), /*     5 a                 */
  S_ST( 'b',	3,        7,     0 ), /*     6 ab                */
  S_ST( 'r',	3,        8,     0 ), /*     7 abb               */
  S_ST( 'e',	3,      258,     0 ), /*     8 abbr              */
  S_ST( 'g',	3,      259,     5 ), /*     9 a                 */
  S_ST( 'l',	3,      260,     9 ), /*    10 a                 */
  S_ST( 'a',	3,      261,     0 ), /*    11 all               */
  S_ST( 'p',	3,       13,    11 ), /*    12 all               */
  S_ST( 'e',	3,       14,     0 ), /*    13 allp              */
  S_ST( 'e',	3,       15,     0 ), /*    14 allpe             */
  S_ST( 'r',	3,      262,     0 ), /*    15 allpee            */
  S_ST( 'u',	3,       17,    10 ), /*    16 a                 */
  S_ST( 't',	3,       18,     0 ), /*    17 au                */
  S_ST( 'o',	3,       21,   263 ), /*    18 aut               */
  S_ST( 'k',	3,       20,     0 ), /*    19 auto              */
  S_ST( 'e',	3,      264,     0 ), /*    20 autok             */
  S_ST( 'm',	3,       22,    19 ), /*    21 auto              */
  S_ST( 'a',	3,      265,     0 ), /*    22 autom             */
  S_ST( 'v',	3,       24,    16 ), /*    23 a                 */
  S_ST( 'e',	3,       25,     0 ), /*    24 av                */
  S_ST( 'r',	3,       26,     0 ), /*    25 ave               */
  S_ST( 'a',	3,       27,     0 ), /*    26 aver              */
  S_ST( 'g',	3,      266,     0 ), /*    27 avera             */
  S_ST( 'b',	3,       75,     4 ), /*    28                   */
  S_ST( 'a',	3,       30,     0 ), /*    29 b                 */
  S_ST( 's',	3,       31,     0 ), /*    30 ba                */
  S_ST( 'e',	3,       32,     0 ), /*    31 bas               */
  S_ST( 'd',	3,       33,     0 ), /*    32 base              */
  S_ST( 'a',	3,       34,     0 ), /*    33 based             */
  S_ST( 't',	3,      267,     0 ), /*    34 baseda            */
  S_ST( 'c',	3,       40,    29 ), /*    35 b                 */
  S_ST( 'l',	3,       37,     0 ), /*    36 bc                */
  S_ST( 'i',	3,       38,     0 ), /*    37 bcl               */
  S_ST( 'e',	3,       39,     0 ), /*    38 bcli              */
  S_ST( 'n',	3,      268,     0 ), /*    39 bclie             */
  S_ST( 'p',	3,       41,    36 ), /*    40 bc                */
  S_ST( 'o',	3,       42,     0 ), /*    41 bcp               */
  S_ST( 'l',	3,       43,     0 ), /*    42 bcpo              */
  S_ST( 'l',	3,       44,     0 ), /*    43 bcpol             */
  S_ST( 'b',	3,       45,     0 ), /*    44 bcpoll            */
  S_ST( 's',	3,       46,     0 ), /*    45 bcpollb           */
  S_ST( 't',	3,       47,     0 ), /*    46 bcpollbs          */
  S_ST( 'e',	3,      269,     0 ), /*    47 bcpollbst         */
  S_ST( 'e',	3,       52,    35 ), /*    48 b                 */
  S_ST( 'a',	3,       50,     0 ), /*    49 be                */
  S_ST( 'c',	3,       51,     0 ), /*    50 bea               */
  S_ST( 'o',	3,      270,     0 ), /*    51 beac              */
  S_ST( 'e',	3,       53,    49 ), /*    52 be                */
  S_ST( 'p',	3,       54,     0 ), /*    53 bee               */
  S_ST( '_',	3,       55,     0 ), /*    54 beep              */
  S_ST( 'd',	3,       56,     0 ), /*    55 beep_             */
  S_ST( 'e',	3,       57,     0 ), /*    56 beep_d            */
  S_ST( 'l',	3,       58,     0 ), /*    57 beep_de           */
  S_ST( 'a',	3,      462,     0 ), /*    58 beep_del          */
  S_ST( 'r',	3,       60,    48 ), /*    59 b                 */
  S_ST( 'o',	3,       61,     0 ), /*    60 br                */
  S_ST( 'a',	3,       62,     0 ), /*    61 bro               */
  S_ST( 'd',	3,       63,     0 ), /*    62 broa              */
  S_ST( 'c',	3,       64,     0 ), /*    63 broad             */
  S_ST( 'a',	3,       65,     0 ), /*    64 broadc            */
  S_ST( 's',	3,      271,     0 ), /*    65 broadca           */
  S_ST( 'c',	3,       67,     0 ), /*    66 broadcast         */
  S_ST( 'l',	3,       68,     0 ), /*    67 broadcastc        */
  S_ST( 'i',	3,       69,     0 ), /*    68 broadcastcl       */
  S_ST( 'e',	3,       70,     0 ), /*    69 broadcastcli      */
  S_ST( 'n',	3,      272,     0 ), /*    70 broadcastclie     */
  S_ST( 'd',	3,       72,    66 ), /*    71 broadcast         */
  S_ST( 'e',	3,       73,     0 ), /*    72 broadcastd        */
  S_ST( 'l',	3,       74,     0 ), /*    73 broadcastde       */
  S_ST( 'a',	3,      273,     0 ), /*    74 broadcastdel      */
  S_ST( 'u',	3,       76,    59 ), /*    75 b                 */
  S_ST( 'r',	3,       77,     0 ), /*    76 bu                */
  S_ST( 's',	3,      274,     0 ), /*    77 bur               */
  S_ST( 'c',	3,      125,    28 ), /*    78                   */
  S_ST( 'a',	3,       80,     0 ), /*    79 c                 */
  S_ST( 'l',	3,       81,     0 ), /*    80 ca                */
  S_ST( 'i',	3,       82,     0 ), /*    81 cal               */
  S_ST( 'b',	3,       83,     0 ), /*    82 cali              */
  S_ST( 'r',	3,       84,     0 ), /*    83 calib             */
  S_ST( 'a',	3,       85,     0 ), /*    84 calibr            */
  S_ST( 't',	3,      275,     0 ), /*    85 calibra           */
  S_ST( 'e',	3,       87,    79 ), /*    86 c                 */
  S_ST( 'i',	3,       88,     0 ), /*    87 ce                */
  S_ST( 'l',	3,       89,     0 ), /*    88 cei               */
  S_ST( 'i',	3,       90,     0 ), /*    89 ceil              */
  S_ST( 'n',	3,      276,     0 ), /*    90 ceili             */
  S_ST( 'h',	3,       92,    86 ), /*    91 c                 */
  S_ST( 'e',	3,       93,     0 ), /*    92 ch                */
  S_ST( 'c',	3,       94,     0 ), /*    93 che               */
  S_ST( 'k',	3,       95,     0 ), /*    94 chec              */
  S_ST( 'h',	3,       96,     0 ), /*    95 check             */
  S_ST( 'a',	3,       97,     0 ), /*    96 checkh            */
  S_ST( 's',	3,      277,     0 ), /*    97 checkha           */
  S_ST( 'l',	3,       99,    91 ), /*    98 c                 */
  S_ST( 'o',	3,      100,     0 ), /*    99 cl                */
  S_ST( 'c',	3,      101,     0 ), /*   100 clo               */
  S_ST( 'k',	3,      102,     0 ), /*   101 cloc              */
  S_ST( 's',	3,      103,     0 ), /*   102 clock             */
  S_ST( 't',	3,      104,     0 ), /*   103 clocks            */
  S_ST( 'a',	3,      105,     0 ), /*   104 clockst           */
  S_ST( 't',	3,      278,     0 ), /*   105 clocksta          */
  S_ST( 'o',	3,      110,    98 ), /*   106 c                 */
  S_ST( 'h',	3,      108,     0 ), /*   107 co                */
  S_ST( 'o',	3,      109,     0 ), /*   108 coh               */
  S_ST( 'r',	3,      279,     0 ), /*   109 coho              */
  S_ST( 'n',	3,      111,   107 ), /*   110 co                */
  S_ST( 't',	3,      112,     0 ), /*   111 con               */
  S_ST( 'r',	3,      113,     0 ), /*   112 cont              */
  S_ST( 'o',	3,      114,     0 ), /*   113 contr             */
  S_ST( 'l',	3,      115,     0 ), /*   114 contro            */
  S_ST( 'k',	3,      116,     0 ), /*   115 control           */
  S_ST( 'e',	3,      280,     0 ), /*   116 controlk          */
  S_ST( 'r',	3,      118,   106 ), /*   117 c                 */
  S_ST( 'y',	3,      119,     0 ), /*   118 cr                */
  S_ST( 'p',	3,      120,     0 ), /*   119 cry               */
  S_ST( 't',	3,      281,     0 ), /*   120 cryp              */
  S_ST( 's',	3,      122,     0 ), /*   121 crypto            */
  S_ST( 't',	3,      123,     0 ), /*   122 cryptos           */
  S_ST( 'a',	3,      124,     0 ), /*   123 cryptost          */
  S_ST( 't',	3,      282,     0 ), /*   124 cryptosta         */
  S_ST( 't',	3,      283,   117 ), /*   125 c                 */
  S_ST( 'd',	3,      171,    78 ), /*   126                   */
  S_ST( 'a',	3,      284,     0 ), /*   127 d                 */
  S_ST( 'e',	3,      141,   127 ), /*   128 d                 */
  S_ST( 'f',	3,      130,     0 ), /*   129 de                */
  S_ST( 'a',	3,      131,     0 ), /*   130 def               */
  S_ST( 'u',	3,      132,     0 ), /*   131 defa              */
  S_ST( 'l',	3,      285,     0 ), /*   132 defau             */
  S_ST( 'l',	3,      134,   129 ), /*   133 de                */
  S_ST( 'r',	3,      135,     0 ), /*   134 del               */
  S_ST( 'e',	3,      136,     0 ), /*   135 delr              */
  S_ST( 's',	3,      137,     0 ), /*   136 delre             */
  S_ST( 't',	3,      138,     0 ), /*   137 delres            */
  S_ST( 'r',	3,      139,     0 ), /*   138 delrest           */
  S_ST( 'i',	3,      140,     0 ), /*   139 delrestr          */
  S_ST( 'c',	3,      286,     0 ), /*   140 delrestri         */
  S_ST( 'v',	3,      142,   133 ), /*   141 de                */
  S_ST( 'i',	3,      143,     0 ), /*   142 dev               */
  S_ST( 'c',	3,      287,     0 ), /*   143 devi              */
  S_ST( 'i',	3,      148,   128 ), /*   144 d                 */
  S_ST( 'g',	3,      146,     0 ), /*   145 di                */
  S_ST( 'e',	3,      147,     0 ), /*   146 dig               */
  S_ST( 's',	3,      288,     0 ), /*   147 dige              */
  S_ST( 's',	3,      155,   145 ), /*   148 di                */
  S_ST( 'a',	3,      150,     0 ), /*   149 dis               */
  S_ST( 'b',	3,      151,     0 ), /*   150 disa              */
  S_ST( 'l',	3,      289,     0 ), /*   151 disab             */
  S_ST( 'c',	3,      153,   149 ), /*   152 dis               */
  S_ST( 'a',	3,      154,     0 ), /*   153 disc              */
  S_ST( 'r',	3,      290,     0 ), /*   154 disca             */
  S_ST( 'p',	3,      156,   152 ), /*   155 dis               */
  S_ST( 'e',	3,      157,     0 ), /*   156 disp              */
  S_ST( 'r',	3,      158,     0 ), /*   157 dispe             */
  S_ST( 's',	3,      159,     0 ), /*   158 disper            */
  S_ST( 'i',	3,      160,     0 ), /*   159 dispers           */
  S_ST( 'o',	3,      291,     0 ), /*   160 dispersi          */
  S_ST( 'r',	3,      168,   144 ), /*   161 d                 */
  S_ST( 'i',	3,      163,     0 ), /*   162 dr                */
  S_ST( 'f',	3,      164,     0 ), /*   163 dri               */
  S_ST( 't',	3,      165,     0 ), /*   164 drif              */
  S_ST( 'f',	3,      166,     0 ), /*   165 drift             */
  S_ST( 'i',	3,      167,     0 ), /*   166 driftf            */
  S_ST( 'l',	3,      293,     0 ), /*   167 driftfi           */
  S_ST( 'o',	3,      294,   162 ), /*   168 dr                */
  S_ST( 's',	3,      170,   161 ), /*   169 d                 */
  S_ST( 'c',	3,      295,     0 ), /*   170 ds                */
  S_ST( 'u',	3,      172,   169 ), /*   171 d                 */
  S_ST( 'r',	3,      173,     0 ), /*   172 du                */
  S_ST( 'a',	3,      174,     0 ), /*   173 dur               */
  S_ST( 't',	3,      175,     0 ), /*   174 dura              */
  S_ST( 'i',	3,      176,     0 ), /*   175 durat             */
  S_ST( 'o',	3,      465,     0 ), /*   176 durati            */
  S_ST( 'e',	3,      182,   126 ), /*   177                   */
  S_ST( 'n',	3,      298,     0 ), /*   178 e                 */
  S_ST( 'a',	3,      180,     0 ), /*   179 en                */
  S_ST( 'b',	3,      181,     0 ), /*   180 ena               */
  S_ST( 'l',	3,      297,     0 ), /*   181 enab              */
  S_ST( 'p',	3,      183,   178 ), /*   182 e                 */
  S_ST( 'e',	3,      184,     0 ), /*   183 ep                */
  S_ST( 'e',	3,      299,     0 ), /*   184 epe               */
  S_ST( 'f',	3,      206,   177 ), /*   185                   */
  S_ST( 'i',	3,      187,     0 ), /*   186 f                 */
  S_ST( 'l',	3,      301,     0 ), /*   187 fi                */
  S_ST( 'g',	3,      189,     0 ), /*   188 file              */
  S_ST( 'e',	3,      302,     0 ), /*   189 fileg             */
  S_ST( 'n',	3,      191,   188 ), /*   190 file              */
  S_ST( 'u',	3,      303,     0 ), /*   191 filen             */
  S_ST( 'l',	3,      196,   186 ), /*   192 f                 */
  S_ST( 'a',	3,      195,     0 ), /*   193 fl                */
  S_ST( 'g',	3,      307,     0 ), /*   194 fla               */
  S_ST( 'k',	3,      308,   194 ), /*   195 fla               */
  S_ST( 'o',	3,      197,   193 ), /*   196 fl                */
  S_ST( 'o',	3,      309,     0 ), /*   197 flo               */
  S_ST( 'r',	3,      199,   192 ), /*   198 f                 */
  S_ST( 'e',	3,      310,     0 ), /*   199 fr                */
  S_ST( '_',	3,      201,     0 ), /*   200 freq              */
  S_ST( 'o',	3,      202,     0 ), /*   201 freq_             */
  S_ST( 'f',	3,      203,     0 ), /*   202 freq_o            */
  S_ST( 'f',	3,      204,     0 ), /*   203 freq_of           */
  S_ST( 's',	3,      205,     0 ), /*   204 freq_off          */
  S_ST( 'e',	3,      466,     0 ), /*   205 freq_offs         */
  S_ST( 'u',	3,      209,   198 ), /*   206 f                 */
  S_ST( 'd',	3,      208,     0 ), /*   207 fu                */
  S_ST( 'g',	3,      311,     0 ), /*   208 fud               */
  S_ST( 'z',	3,      312,   207 ), /*   209 fu                */
  S_ST( 'h',	3,      213,   185 ), /*   210                   */
  S_ST( 'o',	3,      212,     0 ), /*   211 h                 */
  S_ST( 's',	3,      313,     0 ), /*   212 ho                */
  S_ST( 'u',	3,      214,   211 ), /*   213 h                 */
  S_ST( 'f',	3,      215,     0 ), /*   214 hu                */
  S_ST( 'f',	3,      216,     0 ), /*   215 huf               */
  S_ST( 'p',	3,      217,     0 ), /*   216 huff              */
  S_ST( 'u',	3,      218,     0 ), /*   217 huffp             */
  S_ST( 'f',	3,      314,     0 ), /*   218 huffpu            */
  S_ST( 'i',	3,      430,   210 ), /*   219                   */
  S_ST( 'b',	3,      221,     0 ), /*   220 i                 */
  S_ST( 'u',	3,      222,     0 ), /*   221 ib                */
  S_ST( 'r',	3,      223,     0 ), /*   222 ibu               */
  S_ST( 's',	3,      315,     0 ), /*   223 ibur              */
  S_ST( 'd',	3,      225,   220 ), /*   224 i                 */
  S_ST( 'e',	3,      226,     0 ), /*   225 id                */
  S_ST( 'n',	3,      316,     0 ), /*   226 ide               */
  S_ST( 'g',	3,      228,   224 ), /*   227 i                 */
  S_ST( 'n',	3,      229,     0 ), /*   228 ig                */
  S_ST( 'o',	3,      230,     0 ), /*   229 ign               */
  S_ST( 'r',	3,      317,     0 ), /*   230 igno              */
  S_ST( 'h',	3,      232,     0 ), /*   231 ignore            */
  S_ST( 'a',	3,      233,     0 ), /*   232 ignoreh           */
  S_ST( 's',	3,      318,     0 ), /*   233 ignoreha          */
  S_ST( 'n',	3,      257,   227 ), /*   234 i                 */
  S_ST( 'c',	3,      247,     0 ), /*   235 in                */
  S_ST( 'a',	3,      237,     0 ), /*   236 inc               */
  S_ST( 'l',	3,      238,     0 ), /*   237 inca              */
  S_ST( 'l',	3,      239,     0 ), /*   238 incal             */
  S_ST( 'o',	3,      319,     0 ), /*   239 incall            */
  S_ST( 'l',	3,      241,   236 ), /*   240 inc               */
  S_ST( 'u',	3,      242,     0 ), /*   241 incl              */
  S_ST( 'd',	3,      243,     0 ), /*   242 inclu             */
  S_ST( 'e',	3,      244,     0 ), /*   243 includ            */
  S_ST( 'f',	3,      245,     0 ), /*   244 include           */
  S_ST( 'i',	3,      246,     0 ), /*   245 includef          */
  S_ST( 'l',	3,      323,     0 ), /*   246 includefi         */
  S_ST( 'm',	3,      248,   240 ), /*   247 inc               */
  S_ST( 'e',	3,      320,     0 ), /*   248 incm              */
  S_ST( 'i',	3,      250,   235 ), /*   249 in                */
  S_ST( 't',	3,      255,     0 ), /*   250 ini               */
  S_ST( 'a',	3,      252,     0 ), /*   251 init              */
  S_ST( 'l',	3,      253,     0 ), /*   252 inita             */
  S_ST( 'l',	3,      254,     0 ), /*   253 inital            */
  S_ST( 'o',	3,      321,     0 ), /*   254 initall           */
  S_ST( 'm',	3,      256,   251 ), /*   255 init              */
  S_ST( 'e',	3,      322,     0 ), /*   256 initm             */
  S_ST( 't',	3,      292,   249 ), /*   257 in                */
  S_ST( 'v',	1,        0,     0 ), /*   258 T_Abbrev          */
  S_ST( 'e',	0,        0,     0 ), /*   259 T_Age             */
  S_ST( 'l',	0,       12,     0 ), /*   260 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   261 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   262 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   263 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   264 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   265 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   266 T_Average         */
  S_ST( 'e',	1,        0,     0 ), /*   267 T_Basedate        */
  S_ST( 't',	0,        0,     0 ), /*   268 T_Bclient         */
  S_ST( 'p',	0,        0,     0 ), /*   269 T_Bcpollbstep     */
  S_ST( 'n',	0,        0,     0 ), /*   270 T_Beacon          */
  S_ST( 't',	1,       71,     0 ), /*   271 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   272 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   273 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   274 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   275 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   276 T_Ceiling         */
  S_ST( 'h',	0,        0,     0 ), /*   277 T_Checkhash       */
  S_ST( 's',	0,        0,     0 ), /*   278 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   279 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   280 T_ControlKey      */
  S_ST( 'o',	0,      121,     0 ), /*   281 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   282 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   283 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   284 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   285 T_Default         */
  S_ST( 't',	0,        0,     0 ), /*   286 T_Delrestrict     */
  S_ST( 'e',	1,        0,     0 ), /*   287 T_Device          */
  S_ST( 't',	1,        0,     0 ), /*   288 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   289 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   290 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   291 T_Dispersion      */
  S_ST( 'e',	3,      300,     0 ), /*   292 int               */
  S_ST( 'e',	1,        0,     0 ), /*   293 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   294 T_Drop            */
  S_ST( 'p',	0,        0,     0 ), /*   295 T_Dscp            */
  S_ST( '.',	0,        0,     0 ), /*   296 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   297 T_Enable          */
  S_ST( 'd',	0,        0,   179 ), /*   298 T_End             */
  S_ST( 'r',	0,        0,     0 ), /*   299 T_Epeer           */
  S_ST( 'r',	3,      324,     0 ), /*   300 inte              */
  S_ST( 'e',	1,      190,     0 ), /*   301 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   302 T_Filegen         */
  S_ST( 'm',	0,        0,     0 ), /*   303 T_Filenum         */
  S_ST( '1',	0,        0,     0 ), /*   304 T_Flag1           */
  S_ST( '2',	0,        0,   304 ), /*   305 T_Flag2           */
  S_ST( '3',	0,        0,   305 ), /*   306 T_Flag3           */
  S_ST( '4',	0,        0,   306 ), /*   307 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   308 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   309 T_Floor           */
  S_ST( 'q',	0,      200,     0 ), /*   310 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   311 T_Fudge           */
  S_ST( 'z',	0,        0,     0 ), /*   312 T_Fuzz            */
  S_ST( 't',	1,        0,     0 ), /*   313 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   314 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   315 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   316 T_Ident           */
  S_ST( 'e',	0,      231,     0 ), /*   317 T_Ignore          */
  S_ST( 'h',	0,        0,     0 ), /*   318 T_Ignorehash      */
  S_ST( 'c',	0,        0,     0 ), /*   319 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   320 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   321 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   322 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   323 T_Includefile     */
  S_ST( 'f',	3,      326,     0 ), /*   324 inter             */
  S_ST( 'e',	0,        0,     0 ), /*   325 T_Interface       */
  S_ST( 'a',	3,      418,     0 ), /*   326 interf            */
  S_ST( 'o',	0,        0,   234 ), /*   327 T_Io              */
  S_ST( 't',	0,        0,     0 ), /*   328 T_Ippeerlimit     */
  S_ST( '4',	0,        0,     0 ), /*   329 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   330 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   329 ), /*   331 T_Ipv6            */
  S_ST( '6',	0,        0,   330 ), /*   332 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   333 T_Kernel          */
  S_ST( 'y',	0,      335,   484 ), /*   334 T_Key             */
  S_ST( 's',	1,      487,     0 ), /*   335 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   336 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   337 T_Kod             */
  S_ST( 'e',	1,        0,     0 ), /*   338 T_Leapfile        */
  S_ST( 'l',	0,        0,     0 ), /*   339 T_Leapsmearinterval */
  S_ST( 'd',	0,        0,     0 ), /*   340 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   341 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   342 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   343 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   344 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   345 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   346 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   347 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   348 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   349 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   350 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   351 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   352 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   353 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   354 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   355 T_Maxpoll         */
  S_ST( 's',	0,        0,     0 ), /*   356 T_Mdnstries       */
  S_ST( 'm',	0,      587,     0 ), /*   357 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   358 T_Memlock         */
  S_ST( 'k',	0,        0,     0 ), /*   359 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   360 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   361 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   362 T_Minimum         */
  S_ST( 'r',	0,        0,     0 ), /*   363 T_Minjitter       */
  S_ST( 'l',	0,        0,     0 ), /*   364 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   365 T_Minsane         */
  S_ST( 'e',	0,      367,     0 ), /*   366 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   367 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   368 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   369 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   370 T_Mru             */
  S_ST( 'p',	0,        0,     0 ), /*   371 T_Mssntp          */
  S_ST( 't',	2,        0,     0 ), /*   372 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   373 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   374 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   375 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   376 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   377 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   378 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   379 T_Noepeer         */
  S_ST( 'r',	0,        0,     0 ), /*   380 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   381 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   382 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   383 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   384 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   385 T_Notrust         */
  S_ST( 'p',	0,      692,     0 ), /*   386 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   387 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   388 T_NtpSignDsocket  */
  S_ST( 'n',	0,      707,     0 ), /*   389 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   390 T_Orphanwait      */
  S_ST( 'y',	0,        0,     0 ), /*   391 T_PCEdigest       */
  S_ST( 'c',	0,        0,     0 ), /*   392 T_Panic           */
  S_ST( 'r',	1,      734,     0 ), /*   393 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   394 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   395 T_Phone           */
  S_ST( 'd',	0,      742,     0 ), /*   396 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   397 T_Pidfile         */
  S_ST( 'l',	0,      747,     0 ), /*   398 T_Poll            */
  S_ST( 't',	0,        0,     0 ), /*   399 T_PollSkewList    */
  S_ST( 'l',	1,        0,     0 ), /*   400 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   401 T_Port            */
  S_ST( 'a',	1,        0,     0 ), /*   402 T_PpsData         */
  S_ST( 't',	0,        0,     0 ), /*   403 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   404 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   405 T_Protostats      */
  S_ST( 'w',	1,        0,   761 ), /*   406 T_Pw              */
  S_ST( 'e',	1,        0,     0 ), /*   407 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   408 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   409 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   410 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   411 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   412 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   413 T_Revoke          */
  S_ST( 't',	0,        0,     0 ), /*   414 T_Rlimit          */
  S_ST( 'r',	1,        0,     0 ), /*   415 T_Saveconfigdir   */
  S_ST( 'r',	1,      844,     0 ), /*   416 T_Server          */
  S_ST( 'e',	0,        0,     0 ), /*   417 T_Serverresponse  */
  S_ST( 'c',	3,      325,     0 ), /*   418 interfa           */
  S_ST( 'r',	1,        0,     0 ), /*   419 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   420 T_Source          */
  S_ST( 'e',	0,        0,     0 ), /*   421 T_Stacksize       */
  S_ST( 's',	0,        0,     0 ), /*   422 T_Statistics      */
  S_ST( 's',	0,      888,   883 ), /*   423 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   424 T_Statsdir        */
  S_ST( 'p',	0,      896,     0 ), /*   425 T_Step            */
  S_ST( 'k',	0,        0,     0 ), /*   426 T_Stepback        */
  S_ST( 'd',	0,        0,     0 ), /*   427 T_Stepfwd         */
  S_ST( 't',	0,        0,     0 ), /*   428 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   429 T_Stratum         */
  S_ST( 'p',	3,      476,   327 ), /*   430 i                 */
  S_ST( 's',	0,      903,     0 ), /*   431 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   432 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   433 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   434 T_Time1           */
  S_ST( '2',	0,        0,   434 ), /*   435 T_Time2           */
  S_ST( 'a',	1,        0,     0 ), /*   436 T_TimeData        */
  S_ST( 'r',	0,        0,   912 ), /*   437 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   438 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   439 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   440 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   441 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   442 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   443 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   444 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   445 T_Type            */
  S_ST( 'p',	3,      453,     0 ), /*   446 ip                */
  S_ST( 'y',	0,        0,     0 ), /*   447 T_UEcrypto        */
  S_ST( 'y',	0,        0,     0 ), /*   448 T_UEcryptonak     */
  S_ST( 'y',	0,        0,     0 ), /*   449 T_UEdigest        */
  S_ST( 'g',	1,        0,     0 ), /*   450 T_Unconfig        */
  S_ST( 'r',	1,      948,     0 ), /*   451 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   452 T_Version         */
  S_ST( 'e',	3,      459,     0 ), /*   453 ipp               */
  S_ST( 'k',	0,        0,     0 ), /*   454 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   455 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   456 T_Xleave          */
  S_ST( 'e',	0,        0,     0 ), /*   457 T_Xmtnonce        */
  S_ST( 'r',	0,        0,     0 ), /*   458 T_Year            */
  S_ST( 'e',	3,      460,     0 ), /*   459 ippe              */
  S_ST( 'r',	3,      472,     0 ), /*   460 ippee             */
  S_ST( 'e',	0,        0,     0 ), /*   461 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   462 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   463 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   464 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   465 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   466 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   467 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   468 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   469 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   470 T_Proc_Delay      */
  S_ST( 's',	0,        0,   386 ), /*   471 T_Nts             */
  S_ST( 'l',	3,      473,     0 ), /*   472 ippeer            */
  S_ST( 'i',	3,      474,     0 ), /*   473 ippeerl           */
  S_ST( 'm',	3,      475,     0 ), /*   474 ippeerli          */
  S_ST( 'i',	3,      328,     0 ), /*   475 ippeerlim         */
  S_ST( 'v',	3,      331,   446 ), /*   476 ip                */
  S_ST( 'j',	3,      478,   219 ), /*   477                   */
  S_ST( 'i',	3,      479,     0 ), /*   478 j                 */
  S_ST( 't',	3,      480,     0 ), /*   479 ji                */
  S_ST( 't',	3,      481,     0 ), /*   480 jit               */
  S_ST( 'e',	3,      468,     0 ), /*   481 jitt              */
  S_ST( 'k',	3,      489,   477 ), /*   482                   */
  S_ST( 'e',	3,      334,     0 ), /*   483 k                 */
  S_ST( 'r',	3,      485,     0 ), /*   484 ke                */
  S_ST( 'n',	3,      486,     0 ), /*   485 ker               */
  S_ST( 'e',	3,      333,     0 ), /*   486 kern              */
  S_ST( 'd',	3,      488,     0 ), /*   487 keys              */
  S_ST( 'i',	3,      336,     0 ), /*   488 keysd             */
  S_ST( 'o',	3,      337,   483 ), /*   489 k                 */
  S_ST( 'l',	3,      518,   482 ), /*   490                   */
  S_ST( 'e',	3,      492,     0 ), /*   491 l                 */
  S_ST( 'a',	3,      493,     0 ), /*   492 le                */
  S_ST( 'p',	3,      497,     0 ), /*   493 lea               */
  S_ST( 'f',	3,      495,     0 ), /*   494 leap              */
  S_ST( 'i',	3,      496,     0 ), /*   495 leapf             */
  S_ST( 'l',	3,      338,     0 ), /*   496 leapfi            */
  S_ST( 's',	3,      498,   494 ), /*   497 leap              */
  S_ST( 'm',	3,      499,     0 ), /*   498 leaps             */
  S_ST( 'e',	3,      500,     0 ), /*   499 leapsm            */
  S_ST( 'a',	3,      501,     0 ), /*   500 leapsme           */
  S_ST( 'r',	3,      502,     0 ), /*   501 leapsmea          */
  S_ST( 'i',	3,      503,     0 ), /*   502 leapsmear         */
  S_ST( 'n',	3,      504,     0 ), /*   503 leapsmeari        */
  S_ST( 't',	3,      505,     0 ), /*   504 leapsmearin       */
  S_ST( 'e',	3,      506,     0 ), /*   505 leapsmearint      */
  S_ST( 'r',	3,      507,     0 ), /*   506 leapsmearinte     */
  S_ST( 'v',	3,      508,     0 ), /*   507 leapsmearinter    */
  S_ST( 'a',	3,      339,     0 ), /*   508 leapsmearinterv   */
  S_ST( 'i',	3,      515,   491 ), /*   509 l                 */
  S_ST( 'm',	3,      511,     0 ), /*   510 li                */
  S_ST( 'i',	3,      512,     0 ), /*   511 lim               */
  S_ST( 't',	3,      513,     0 ), /*   512 limi              */
  S_ST( 'e',	3,      340,     0 ), /*   513 limit             */
  S_ST( 'n',	3,      341,   510 ), /*   514 li                */
  S_ST( 's',	3,      516,   514 ), /*   515 li                */
  S_ST( 't',	3,      517,     0 ), /*   516 lis               */
  S_ST( 'e',	3,      342,     0 ), /*   517 list              */
  S_ST( 'o',	3,      534,   509 ), /*   518 l                 */
  S_ST( 'g',	3,      525,     0 ), /*   519 lo                */
  S_ST( 'c',	3,      521,     0 ), /*   520 log               */
  S_ST( 'o',	3,      522,     0 ), /*   521 logc              */
  S_ST( 'n',	3,      523,     0 ), /*   522 logco             */
  S_ST( 'f',	3,      524,     0 ), /*   523 logcon            */
  S_ST( 'i',	3,      343,     0 ), /*   524 logconf           */
  S_ST( 'f',	3,      526,   520 ), /*   525 log               */
  S_ST( 'i',	3,      527,     0 ), /*   526 logf              */
  S_ST( 'l',	3,      344,     0 ), /*   527 logfi             */
  S_ST( 'o',	3,      529,   519 ), /*   528 lo                */
  S_ST( 'p',	3,      530,     0 ), /*   529 loo               */
  S_ST( 's',	3,      531,     0 ), /*   530 loop              */
  S_ST( 't',	3,      532,     0 ), /*   531 loops             */
  S_ST( 'a',	3,      533,     0 ), /*   532 loopst            */
  S_ST( 't',	3,      345,     0 ), /*   533 loopsta           */
  S_ST( 'w',	3,      535,   528 ), /*   534 lo                */
  S_ST( 'p',	3,      536,     0 ), /*   535 low               */
  S_ST( 'r',	3,      537,     0 ), /*   536 lowp              */
  S_ST( 'i',	3,      538,     0 ), /*   537 lowpr             */
  S_ST( 'o',	3,      539,     0 ), /*   538 lowpri            */
  S_ST( 't',	3,      540,     0 ), /*   539 lowprio           */
  S_ST( 'r',	3,      541,     0 ), /*   540 lowpriot          */
  S_ST( 'a',	3,      346,     0 ), /*   541 lowpriotr         */
  S_ST( 'm',	3,      628,   490 ), /*   542                   */
  S_ST( 'a',	3,      561,     0 ), /*   543 m                 */
  S_ST( 'n',	3,      545,     0 ), /*   544 ma                */
  S_ST( 'y',	3,      546,     0 ), /*   545 man               */
  S_ST( 'c',	3,      547,     0 ), /*   546 many              */
  S_ST( 'a',	3,      548,     0 ), /*   547 manyc             */
  S_ST( 's',	3,      549,     0 ), /*   548 manyca            */
  S_ST( 't',	3,      555,     0 ), /*   549 manycas           */
  S_ST( 'c',	3,      551,     0 ), /*   550 manycast          */
  S_ST( 'l',	3,      552,     0 ), /*   551 manycastc         */
  S_ST( 'i',	3,      553,     0 ), /*   552 manycastcl        */
  S_ST( 'e',	3,      554,     0 ), /*   553 manycastcli       */
  S_ST( 'n',	3,      347,     0 ), /*   554 manycastclie      */
  S_ST( 's',	3,      556,   550 ), /*   555 manycast          */
  S_ST( 'e',	3,      557,     0 ), /*   556 manycasts         */
  S_ST( 'r',	3,      558,     0 ), /*   557 manycastse        */
  S_ST( 'v',	3,      559,     0 ), /*   558 manycastser       */
  S_ST( 'e',	3,      348,     0 ), /*   559 manycastserv      */
  S_ST( 's',	3,      349,   544 ), /*   560 ma                */
  S_ST( 'x',	3,      576,   560 ), /*   561 ma                */
  S_ST( 'a',	3,      563,     0 ), /*   562 max               */
  S_ST( 'g',	3,      350,     0 ), /*   563 maxa              */
  S_ST( 'c',	3,      565,   562 ), /*   564 max               */
  S_ST( 'l',	3,      566,     0 ), /*   565 maxc              */
  S_ST( 'o',	3,      567,     0 ), /*   566 maxcl             */
  S_ST( 'c',	3,      351,     0 ), /*   567 maxclo            */
  S_ST( 'd',	3,      572,   564 ), /*   568 max               */
  S_ST( 'e',	3,      570,     0 ), /*   569 maxd              */
  S_ST( 'p',	3,      571,     0 ), /*   570 maxde             */
  S_ST( 't',	3,      352,     0 ), /*   571 maxdep            */
  S_ST( 'i',	3,      573,   569 ), /*   572 maxd              */
  S_ST( 's',	3,      353,     0 ), /*   573 maxdi             */
  S_ST( 'm',	3,      575,   568 ), /*   574 max               */
  S_ST( 'e',	3,      354,     0 ), /*   575 maxm              */
  S_ST( 'p',	3,      577,   574 ), /*   576 max               */
  S_ST( 'o',	3,      578,     0 ), /*   577 maxp              */
  S_ST( 'l',	3,      355,     0 ), /*   578 maxpo             */
  S_ST( 'd',	3,      580,   543 ), /*   579 m                 */
  S_ST( 'n',	3,      581,     0 ), /*   580 md                */
  S_ST( 's',	3,      582,     0 ), /*   581 mdn               */
  S_ST( 't',	3,      583,     0 ), /*   582 mdns              */
  S_ST( 'r',	3,      584,     0 ), /*   583 mdnst             */
  S_ST( 'i',	3,      585,     0 ), /*   584 mdnstr            */
  S_ST( 'e',	3,      356,     0 ), /*   585 mdnstri           */
  S_ST( 'e',	3,      357,   579 ), /*   586 m                 */
  S_ST( 'l',	3,      588,     0 ), /*   587 mem               */
  S_ST( 'o',	3,      589,     0 ), /*   588 meml              */
  S_ST( 'c',	3,      358,     0 ), /*   589 memlo             */
  S_ST( 'i',	3,      591,   586 ), /*   590 m                 */
  S_ST( 'n',	3,      613,     0 ), /*   591 mi                */
  S_ST( 'c',	3,      593,     0 ), /*   592 min               */
  S_ST( 'l',	3,      594,     0 ), /*   593 minc              */
  S_ST( 'o',	3,      595,     0 ), /*   594 mincl             */
  S_ST( 'c',	3,      359,     0 ), /*   595 minclo            */
  S_ST( 'd',	3,      600,   592 ), /*   596 min               */
  S_ST( 'e',	3,      598,     0 ), /*   597 mind              */
  S_ST( 'p',	3,      599,     0 ), /*   598 minde             */
  S_ST( 't',	3,      360,     0 ), /*   599 mindep            */
  S_ST( 'i',	3,      601,   597 ), /*   600 mind              */
  S_ST( 's',	3,      361,     0 ), /*   601 mindi             */
  S_ST( 'i',	3,      603,   596 ), /*   602 min               */
  S_ST( 'm',	3,      604,     0 ), /*   603 mini              */
  S_ST( 'u',	3,      362,     0 ), /*   604 minim             */
  S_ST( 'j',	3,      606,   602 ), /*   605 min               */
  S_ST( 'i',	3,      607,     0 ), /*   606 minj              */
  S_ST( 't',	3,      608,     0 ), /*   607 minji             */
  S_ST( 't',	3,      609,     0 ), /*   608 minjit            */
  S_ST( 'e',	3,      363,     0 ), /*   609 minjitt           */
  S_ST( 'p',	3,      611,   605 ), /*   610 min               */
  S_ST( 'o',	3,      612,     0 ), /*   611 minp              */
  S_ST( 'l',	3,      364,     0 ), /*   612 minpo             */
  S_ST( 's',	3,      614,   610 ), /*   613 min               */
  S_ST( 'a',	3,      615,     0 ), /*   614 mins              */
  S_ST( 'n',	3,      365,     0 ), /*   615 minsa             */
  S_ST( 'o',	3,      618,   590 ), /*   616 m                 */
  S_ST( 'd',	3,      366,     0 ), /*   617 mo                */
  S_ST( 'n',	3,      622,   617 ), /*   618 mo                */
  S_ST( 'i',	3,      620,     0 ), /*   619 mon               */
  S_ST( 't',	3,      621,     0 ), /*   620 moni              */
  S_ST( 'o',	3,      368,     0 ), /*   621 monit             */
  S_ST( 't',	3,      369,   619 ), /*   622 mon               */
  S_ST( 'r',	3,      370,   616 ), /*   623 m                 */
  S_ST( 's',	3,      625,   623 ), /*   624 m                 */
  S_ST( 's',	3,      626,     0 ), /*   625 ms                */
  S_ST( 'n',	3,      627,     0 ), /*   626 mss               */
  S_ST( 't',	3,      371,     0 ), /*   627 mssn              */
  S_ST( 'u',	3,      629,   624 ), /*   628 m                 */
  S_ST( 'l',	3,      630,     0 ), /*   629 mu                */
  S_ST( 't',	3,      631,     0 ), /*   630 mul               */
  S_ST( 'i',	3,      632,     0 ), /*   631 mult              */
  S_ST( 'c',	3,      633,     0 ), /*   632 multi             */
  S_ST( 'a',	3,      634,     0 ), /*   633 multic            */
  S_ST( 's',	3,      635,     0 ), /*   634 multica           */
  S_ST( 't',	3,      636,     0 ), /*   635 multicas          */
  S_ST( 'c',	3,      637,     0 ), /*   636 multicast         */
  S_ST( 'l',	3,      638,     0 ), /*   637 multicastc        */
  S_ST( 'i',	3,      639,     0 ), /*   638 multicastcl       */
  S_ST( 'e',	3,      640,     0 ), /*   639 multicastcli      */
  S_ST( 'n',	3,      372,     0 ), /*   640 multicastclie     */
  S_ST( 'n',	3,      688,   542 ), /*   641                   */
  S_ST( 'i',	3,      373,     0 ), /*   642 n                 */
  S_ST( 'o',	3,      683,   642 ), /*   643 n                 */
  S_ST( 'e',	3,      645,     0 ), /*   644 no                */
  S_ST( 'p',	3,      646,     0 ), /*   645 noe               */
  S_ST( 'e',	3,      647,     0 ), /*   646 noep              */
  S_ST( 'e',	3,      379,     0 ), /*   647 noepe             */
  S_ST( 'l',	3,      649,   644 ), /*   648 no                */
  S_ST( 'i',	3,      650,     0 ), /*   649 nol               */
  S_ST( 'n',	3,      374,     0 ), /*   650 noli              */
  S_ST( 'm',	3,      656,   648 ), /*   651 no                */
  S_ST( 'o',	3,      653,     0 ), /*   652 nom               */
  S_ST( 'd',	3,      654,     0 ), /*   653 nomo              */
  S_ST( 'i',	3,      655,     0 ), /*   654 nomod             */
  S_ST( 'f',	3,      375,     0 ), /*   655 nomodi            */
  S_ST( 'r',	3,      657,   652 ), /*   656 nom               */
  S_ST( 'u',	3,      658,     0 ), /*   657 nomr              */
  S_ST( 'l',	3,      659,     0 ), /*   658 nomru             */
  S_ST( 'i',	3,      660,     0 ), /*   659 nomrul            */
  S_ST( 's',	3,      376,     0 ), /*   660 nomruli           */
  S_ST( 'n',	3,      662,   651 ), /*   661 no                */
  S_ST( 'v',	3,      663,   377 ), /*   662 non               */
  S_ST( 'o',	3,      664,     0 ), /*   663 nonv              */
  S_ST( 'l',	3,      665,     0 ), /*   664 nonvo             */
  S_ST( 'a',	3,      666,     0 ), /*   665 nonvol            */
  S_ST( 't',	3,      667,     0 ), /*   666 nonvola           */
  S_ST( 'i',	3,      668,     0 ), /*   667 nonvolat          */
  S_ST( 'l',	3,      378,     0 ), /*   668 nonvolati         */
  S_ST( 'p',	3,      670,   661 ), /*   669 no                */
  S_ST( 'e',	3,      671,     0 ), /*   670 nop               */
  S_ST( 'e',	3,      380,     0 ), /*   671 nope              */
  S_ST( 'q',	3,      673,   669 ), /*   672 no                */
  S_ST( 'u',	3,      674,     0 ), /*   673 noq               */
  S_ST( 'e',	3,      675,     0 ), /*   674 noqu              */
  S_ST( 'r',	3,      381,     0 ), /*   675 noque             */
  S_ST( 's',	3,      677,   672 ), /*   676 no                */
  S_ST( 'e',	3,      681,     0 ), /*   677 nos               */
  S_ST( 'l',	3,      679,     0 ), /*   678 nose              */
  S_ST( 'e',	3,      680,     0 ), /*   679 nosel             */
  S_ST( 'c',	3,      382,     0 ), /*   680 nosele            */
  S_ST( 'r',	3,      682,   678 ), /*   681 nose              */
  S_ST( 'v',	3,      383,     0 ), /*   682 noser             */
  S_ST( 't',	3,      684,   676 ), /*   683 no                */
  S_ST( 'r',	3,      686,     0 ), /*   684 not               */
  S_ST( 'a',	3,      384,     0 ), /*   685 notr              */
  S_ST( 'u',	3,      687,   685 ), /*   686 notr              */
  S_ST( 's',	3,      385,     0 ), /*   687 notru             */
  S_ST( 't',	3,      471,   643 ), /*   688 n                 */
  S_ST( 'p',	3,      690,     0 ), /*   689 ntp               */
  S_ST( 'o',	3,      691,     0 ), /*   690 ntpp              */
  S_ST( 'r',	3,      387,     0 ), /*   691 ntppo             */
  S_ST( 's',	3,      693,   689 ), /*   692 ntp               */
  S_ST( 'i',	3,      694,     0 ), /*   693 ntps              */
  S_ST( 'g',	3,      695,     0 ), /*   694 ntpsi             */
  S_ST( 'n',	3,      696,     0 ), /*   695 ntpsig            */
  S_ST( 'd',	3,      697,     0 ), /*   696 ntpsign           */
  S_ST( 's',	3,      698,     0 ), /*   697 ntpsignd          */
  S_ST( 'o',	3,      699,     0 ), /*   698 ntpsignds         */
  S_ST( 'c',	3,      700,     0 ), /*   699 ntpsigndso        */
  S_ST( 'k',	3,      701,     0 ), /*   700 ntpsigndsoc       */
  S_ST( 'e',	3,      388,     0 ), /*   701 ntpsigndsock      */
  S_ST( 'o',	3,      703,   641 ), /*   702                   */
  S_ST( 'r',	3,      704,     0 ), /*   703 o                 */
  S_ST( 'p',	3,      705,     0 ), /*   704 or                */
  S_ST( 'h',	3,      706,     0 ), /*   705 orp               */
  S_ST( 'a',	3,      389,     0 ), /*   706 orph              */
  S_ST( 'w',	3,      708,     0 ), /*   707 orphan            */
  S_ST( 'a',	3,      709,     0 ), /*   708 orphanw           */
  S_ST( 'i',	3,      390,     0 ), /*   709 orphanwa          */
  S_ST( 'p',	3,      406,   702 ), /*   710                   */
  S_ST( 'a',	3,      712,     0 ), /*   711 p                 */
  S_ST( 'n',	3,      713,     0 ), /*   712 pa                */
  S_ST( 'i',	3,      392,     0 ), /*   713 pan               */
  S_ST( 'e',	3,      715,   711 ), /*   714 p                 */
  S_ST( 'e',	3,      393,     0 ), /*   715 pe                */
  S_ST( '_',	3,      717,     0 ), /*   716 peer              */
  S_ST( 'c',	3,      718,     0 ), /*   717 peer_             */
  S_ST( 'l',	3,      719,     0 ), /*   718 peer_c            */
  S_ST( 'e',	3,      720,     0 ), /*   719 peer_cl           */
  S_ST( 'a',	3,      721,     0 ), /*   720 peer_cle          */
  S_ST( 'r',	3,      722,     0 ), /*   721 peer_clea         */
  S_ST( '_',	3,      723,     0 ), /*   722 peer_clear        */
  S_ST( 'd',	3,      724,     0 ), /*   723 peer_clear_       */
  S_ST( 'i',	3,      725,     0 ), /*   724 peer_clear_d      */
  S_ST( 'g',	3,      726,     0 ), /*   725 peer_clear_di     */
  S_ST( 'e',	3,      727,     0 ), /*   726 peer_clear_dig    */
  S_ST( 's',	3,      728,     0 ), /*   727 peer_clear_dige   */
  S_ST( 't',	3,      729,     0 ), /*   728 peer_clear_diges  */
  S_ST( '_',	3,      730,     0 ), /*   729 peer_clear_digest */
  S_ST( 'e',	3,      731,     0 ), /*   730 peer_clear_digest_ */
  S_ST( 'a',	3,      732,     0 ), /*   731 peer_clear_digest_e */
  S_ST( 'r',	3,      733,     0 ), /*   732 peer_clear_digest_ea */
  S_ST( 'l',	3,      391,     0 ), /*   733 peer_clear_digest_ear */
  S_ST( 's',	3,      735,   716 ), /*   734 peer              */
  S_ST( 't',	3,      736,     0 ), /*   735 peers             */
  S_ST( 'a',	3,      737,     0 ), /*   736 peerst            */
  S_ST( 't',	3,      394,     0 ), /*   737 peersta           */
  S_ST( 'h',	3,      739,   714 ), /*   738 p                 */
  S_ST( 'o',	3,      740,     0 ), /*   739 ph                */
  S_ST( 'n',	3,      395,     0 ), /*   740 pho               */
  S_ST( 'i',	3,      396,   738 ), /*   741 p                 */
  S_ST( 'f',	3,      743,     0 ), /*   742 pid               */
  S_ST( 'i',	3,      744,     0 ), /*   743 pidf              */
  S_ST( 'l',	3,      397,     0 ), /*   744 pidfi             */
  S_ST( 'o',	3,      755,   741 ), /*   745 p                 */
  S_ST( 'l',	3,      398,     0 ), /*   746 po                */
  S_ST( 's',	3,      748,     0 ), /*   747 poll              */
  S_ST( 'k',	3,      749,     0 ), /*   748 polls             */
  S_ST( 'e',	3,      750,     0 ), /*   749 pollsk            */
  S_ST( 'w',	3,      751,     0 ), /*   750 pollske           */
  S_ST( 'l',	3,      752,     0 ), /*   751 pollskew          */
  S_ST( 'i',	3,      753,     0 ), /*   752 pollskewl         */
  S_ST( 's',	3,      399,     0 ), /*   753 pollskewli        */
  S_ST( 'o',	3,      400,   746 ), /*   754 po                */
  S_ST( 'r',	3,      401,   754 ), /*   755 po                */
  S_ST( 'p',	3,      757,   745 ), /*   756 p                 */
  S_ST( 's',	3,      758,     0 ), /*   757 pp                */
  S_ST( 'd',	3,      759,     0 ), /*   758 pps               */
  S_ST( 'a',	3,      760,     0 ), /*   759 ppsd              */
  S_ST( 't',	3,      402,     0 ), /*   760 ppsda             */
  S_ST( 'r',	3,      768,   756 ), /*   761 p                 */
  S_ST( 'e',	3,      766,     0 ), /*   762 pr                */
  S_ST( 'e',	3,      764,     0 ), /*   763 pre               */
  S_ST( 'm',	3,      765,     0 ), /*   764 pree              */
  S_ST( 'p',	3,      403,     0 ), /*   765 preem             */
  S_ST( 'f',	3,      767,   763 ), /*   766 pre               */
  S_ST( 'e',	3,      404,     0 ), /*   767 pref              */
  S_ST( 'o',	3,      781,   762 ), /*   768 pr                */
  S_ST( 'c',	3,      770,     0 ), /*   769 pro               */
  S_ST( '_',	3,      771,     0 ), /*   770 proc              */
  S_ST( 'd',	3,      772,     0 ), /*   771 proc_             */
  S_ST( 'e',	3,      773,     0 ), /*   772 proc_d            */
  S_ST( 'l',	3,      774,     0 ), /*   773 proc_de           */
  S_ST( 'a',	3,      470,     0 ), /*   774 proc_del          */
  S_ST( 'p',	3,      776,   769 ), /*   775 pro               */
  S_ST( '_',	3,      777,     0 ), /*   776 prop              */
  S_ST( 'd',	3,      778,     0 ), /*   777 prop_             */
  S_ST( 'e',	3,      779,     0 ), /*   778 prop_d            */
  S_ST( 'l',	3,      780,     0 ), /*   779 prop_de           */
  S_ST( 'a',	3,      469,     0 ), /*   780 prop_del          */
  S_ST( 't',	3,      782,   775 ), /*   781 pro               */
  S_ST( 'o',	3,      783,     0 ), /*   782 prot              */
  S_ST( 's',	3,      784,     0 ), /*   783 proto             */
  S_ST( 't',	3,      785,     0 ), /*   784 protos            */
  S_ST( 'a',	3,      786,     0 ), /*   785 protost           */
  S_ST( 't',	3,      405,     0 ), /*   786 protosta          */
  S_ST( 'r',	3,      818,   710 ), /*   787                   */
  S_ST( 'a',	3,      794,     0 ), /*   788 r                 */
  S_ST( 'n',	3,      790,     0 ), /*   789 ra                */
  S_ST( 'd',	3,      791,     0 ), /*   790 ran               */
  S_ST( 'f',	3,      792,     0 ), /*   791 rand              */
  S_ST( 'i',	3,      793,     0 ), /*   792 randf             */
  S_ST( 'l',	3,      407,     0 ), /*   793 randfi            */
  S_ST( 'w',	3,      795,   789 ), /*   794 ra                */
  S_ST( 's',	3,      796,     0 ), /*   795 raw               */
  S_ST( 't',	3,      797,     0 ), /*   796 raws              */
  S_ST( 'a',	3,      798,     0 ), /*   797 rawst             */
  S_ST( 't',	3,      408,     0 ), /*   798 rawsta            */
  S_ST( 'e',	3,      815,   788 ), /*   799 r                 */
  S_ST( 'f',	3,      801,     0 ), /*   800 re                */
  S_ST( 'i',	3,      409,     0 ), /*   801 ref               */
  S_ST( 'q',	3,      803,   800 ), /*   802 re                */
  S_ST( 'u',	3,      804,     0 ), /*   803 req               */
  S_ST( 'e',	3,      805,     0 ), /*   804 requ              */
  S_ST( 's',	3,      806,     0 ), /*   805 reque             */
  S_ST( 't',	3,      807,     0 ), /*   806 reques            */
  S_ST( 'k',	3,      808,     0 ), /*   807 request           */
  S_ST( 'e',	3,      410,     0 ), /*   808 requestk          */
  S_ST( 's',	3,      811,   802 ), /*   809 re                */
  S_ST( 'e',	3,      411,     0 ), /*   810 res               */
  S_ST( 't',	3,      812,   810 ), /*   811 res               */
  S_ST( 'r',	3,      813,     0 ), /*   812 rest              */
  S_ST( 'i',	3,      814,     0 ), /*   813 restr             */
  S_ST( 'c',	3,      412,     0 ), /*   814 restri            */
  S_ST( 'v',	3,      816,   809 ), /*   815 re                */
  S_ST( 'o',	3,      817,     0 ), /*   816 rev               */
  S_ST( 'k',	3,      413,     0 ), /*   817 revo              */
  S_ST( 'l',	3,      819,   799 ), /*   818 r                 */
  S_ST( 'i',	3,      820,     0 ), /*   819 rl                */
  S_ST( 'm',	3,      821,     0 ), /*   820 rli               */
  S_ST( 'i',	3,      414,     0 ), /*   821 rlim              */
  S_ST( 's',	3,      902,   787 ), /*   822                   */
  S_ST( 'a',	3,      824,     0 ), /*   823 s                 */
  S_ST( 'v',	3,      825,     0 ), /*   824 sa                */
  S_ST( 'e',	3,      826,     0 ), /*   825 sav               */
  S_ST( 'c',	3,      827,     0 ), /*   826 save              */
  S_ST( 'o',	3,      828,     0 ), /*   827 savec             */
  S_ST( 'n',	3,      829,     0 ), /*   828 saveco            */
  S_ST( 'f',	3,      830,     0 ), /*   829 savecon           */
  S_ST( 'i',	3,      831,     0 ), /*   830 saveconf          */
  S_ST( 'g',	3,      832,     0 ), /*   831 saveconfi         */
  S_ST( 'd',	3,      833,     0 ), /*   832 saveconfig        */
  S_ST( 'i',	3,      415,     0 ), /*   833 saveconfigd       */
  S_ST( 'e',	3,      851,   823 ), /*   834 s                 */
  S_ST( 'r',	3,      836,     0 ), /*   835 se                */
  S_ST( 'v',	3,      837,     0 ), /*   836 ser               */
  S_ST( 'e',	3,      416,     0 ), /*   837 serv              */
  S_ST( '_',	3,      839,     0 ), /*   838 server            */
  S_ST( 'o',	3,      840,     0 ), /*   839 server_           */
  S_ST( 'f',	3,      841,     0 ), /*   840 server_o          */
  S_ST( 'f',	3,      842,     0 ), /*   841 server_of         */
  S_ST( 's',	3,      843,     0 ), /*   842 server_off        */
  S_ST( 'e',	3,      464,     0 ), /*   843 server_offs       */
  S_ST( 'r',	3,      845,   838 ), /*   844 server            */
  S_ST( 'e',	3,      846,     0 ), /*   845 serverr           */
  S_ST( 's',	3,      847,     0 ), /*   846 serverre          */
  S_ST( 'p',	3,      848,     0 ), /*   847 serverres         */
  S_ST( 'o',	3,      849,     0 ), /*   848 serverresp        */
  S_ST( 'n',	3,      850,     0 ), /*   849 serverrespo       */
  S_ST( 's',	3,      417,     0 ), /*   850 serverrespon      */
  S_ST( 't',	3,      852,   835 ), /*   851 se                */
  S_ST( 'v',	3,      853,     0 ), /*   852 set               */
  S_ST( 'a',	3,      419,     0 ), /*   853 setv              */
  S_ST( 'i',	3,      855,   834 ), /*   854 s                 */
  S_ST( 'm',	3,      856,     0 ), /*   855 si                */
  S_ST( 'u',	3,      857,     0 ), /*   856 sim               */
  S_ST( 'l',	3,      858,     0 ), /*   857 simu              */
  S_ST( 'a',	3,      859,     0 ), /*   858 simul             */
  S_ST( 't',	3,      860,     0 ), /*   859 simula            */
  S_ST( 'i',	3,      861,   461 ), /*   860 simulat           */
  S_ST( 'o',	3,      862,     0 ), /*   861 simulati          */
  S_ST( 'n',	3,      863,     0 ), /*   862 simulatio         */
  S_ST( '_',	3,      864,     0 ), /*   863 simulation        */
  S_ST( 'd',	3,      865,     0 ), /*   864 simulation_       */
  S_ST( 'u',	3,      866,     0 ), /*   865 simulation_d      */
  S_ST( 'r',	3,      867,     0 ), /*   866 simulation_du     */
  S_ST( 'a',	3,      868,     0 ), /*   867 simulation_dur    */
  S_ST( 't',	3,      869,     0 ), /*   868 simulation_dura   */
  S_ST( 'i',	3,      870,     0 ), /*   869 simulation_durat  */
  S_ST( 'o',	3,      463,     0 ), /*   870 simulation_durati */
  S_ST( 'o',	3,      872,   854 ), /*   871 s                 */
  S_ST( 'u',	3,      873,     0 ), /*   872 so                */
  S_ST( 'r',	3,      874,     0 ), /*   873 sou               */
  S_ST( 'c',	3,      420,     0 ), /*   874 sour              */
  S_ST( 't',	3,      898,   871 ), /*   875 s                 */
  S_ST( 'a',	3,      882,     0 ), /*   876 st                */
  S_ST( 'c',	3,      878,     0 ), /*   877 sta               */
  S_ST( 'k',	3,      879,     0 ), /*   878 stac              */
  S_ST( 's',	3,      880,     0 ), /*   879 stack             */
  S_ST( 'i',	3,      881,     0 ), /*   880 stacks            */
  S_ST( 'z',	3,      421,     0 ), /*   881 stacksi           */
  S_ST( 't',	3,      423,   877 ), /*   882 sta               */
  S_ST( 'i',	3,      884,     0 ), /*   883 stat              */
  S_ST( 's',	3,      885,     0 ), /*   884 stati             */
  S_ST( 't',	3,      886,     0 ), /*   885 statis            */
  S_ST( 'i',	3,      887,     0 ), /*   886 statist           */
  S_ST( 'c',	3,      422,     0 ), /*   887 statisti          */
  S_ST( 'd',	3,      889,     0 ), /*   888 stats             */
  S_ST( 'i',	3,      424,     0 ), /*   889 statsd            */
  S_ST( 'e',	3,      425,   876 ), /*   890 st                */
  S_ST( 'b',	3,      892,     0 ), /*   891 step              */
  S_ST( 'a',	3,      893,     0 ), /*   892 stepb             */
  S_ST( 'c',	3,      426,     0 ), /*   893 stepba            */
  S_ST( 'f',	3,      895,   891 ), /*   894 step              */
  S_ST( 'w',	3,      427,     0 ), /*   895 stepf             */
  S_ST( 'o',	3,      897,   894 ), /*   896 step              */
  S_ST( 'u',	3,      428,     0 ), /*   897 stepo             */
  S_ST( 'r',	3,      899,   890 ), /*   898 st                */
  S_ST( 'a',	3,      900,     0 ), /*   899 str               */
  S_ST( 't',	3,      901,     0 ), /*   900 stra              */
  S_ST( 'u',	3,      429,     0 ), /*   901 strat             */
  S_ST( 'y',	3,      431,   875 ), /*   902 s                 */
  S_ST( 's',	3,      904,     0 ), /*   903 sys               */
  S_ST( 't',	3,      905,     0 ), /*   904 syss              */
  S_ST( 'a',	3,      906,     0 ), /*   905 sysst             */
  S_ST( 't',	3,      432,     0 ), /*   906 syssta            */
  S_ST( 't',	3,      936,   822 ), /*   907                   */
  S_ST( 'i',	3,      922,     0 ), /*   908 t                 */
  S_ST( 'c',	3,      433,     0 ), /*   909 ti                */
  S_ST( 'm',	3,      915,   909 ), /*   910 ti                */
  S_ST( 'e',	3,      437,     0 ), /*   911 tim               */
  S_ST( 'd',	3,      913,   435 ), /*   912 time              */
  S_ST( 'a',	3,      914,     0 ), /*   913 timed             */
  S_ST( 't',	3,      436,     0 ), /*   914 timeda            */
  S_ST( 'i',	3,      916,   911 ), /*   915 tim               */
  S_ST( 'n',	3,      917,     0 ), /*   916 timi              */
  S_ST( 'g',	3,      918,     0 ), /*   917 timin             */
  S_ST( 's',	3,      919,     0 ), /*   918 timing            */
  S_ST( 't',	3,      920,     0 ), /*   919 timings           */
  S_ST( 'a',	3,      921,     0 ), /*   920 timingst          */
  S_ST( 't',	3,      438,     0 ), /*   921 timingsta         */
  S_ST( 'n',	3,      923,   910 ), /*   922 ti                */
  S_ST( 'k',	3,      924,     0 ), /*   923 tin               */
  S_ST( 'e',	3,      439,     0 ), /*   924 tink              */
  S_ST( 'o',	3,      440,   908 ), /*   925 t                 */
  S_ST( 'r',	3,      928,   925 ), /*   926 t                 */
  S_ST( 'a',	3,      441,     0 ), /*   927 tr                */
  S_ST( 'u',	3,      929,   927 ), /*   928 tr                */
  S_ST( 's',	3,      930,   442 ), /*   929 tru               */
  S_ST( 't',	3,      931,     0 ), /*   930 trus              */
  S_ST( 'e',	3,      932,     0 ), /*   931 trust             */
  S_ST( 'd',	3,      933,     0 ), /*   932 truste            */
  S_ST( 'k',	3,      934,     0 ), /*   933 trusted           */
  S_ST( 'e',	3,      443,     0 ), /*   934 trustedk          */
  S_ST( 't',	3,      444,   926 ), /*   935 t                 */
  S_ST( 'y',	3,      937,   935 ), /*   936 t                 */
  S_ST( 'p',	3,      445,     0 ), /*   937 ty                */
  S_ST( 'u',	3,      939,   907 ), /*   938                   */
  S_ST( 'n',	3,      945,     0 ), /*   939 u                 */
  S_ST( 'c',	3,      941,     0 ), /*   940 un                */
  S_ST( 'o',	3,      942,     0 ), /*   941 unc               */
  S_ST( 'n',	3,      943,     0 ), /*   942 unco              */
  S_ST( 'f',	3,      944,     0 ), /*   943 uncon             */
  S_ST( 'i',	3,      450,     0 ), /*   944 unconf            */
  S_ST( 'p',	3,      946,   940 ), /*   945 un                */
  S_ST( 'e',	3,      947,     0 ), /*   946 unp               */
  S_ST( 'e',	3,      451,     0 ), /*   947 unpe              */
  S_ST( '_',	3,      968,     0 ), /*   948 unpeer            */
  S_ST( 'c',	3,      950,     0 ), /*   949 unpeer_           */
  S_ST( 'r',	3,      951,     0 ), /*   950 unpeer_c          */
  S_ST( 'y',	3,      952,     0 ), /*   951 unpeer_cr         */
  S_ST( 'p',	3,      953,     0 ), /*   952 unpeer_cry        */
  S_ST( 't',	3,      954,     0 ), /*   953 unpeer_cryp       */
  S_ST( 'o',	3,      955,     0 ), /*   954 unpeer_crypt      */
  S_ST( '_',	3,      960,     0 ), /*   955 unpeer_crypto     */
  S_ST( 'e',	3,      957,     0 ), /*   956 unpeer_crypto_    */
  S_ST( 'a',	3,      958,     0 ), /*   957 unpeer_crypto_e   */
  S_ST( 'r',	3,      959,     0 ), /*   958 unpeer_crypto_ea  */
  S_ST( 'l',	3,      447,     0 ), /*   959 unpeer_crypto_ear */
  S_ST( 'n',	3,      961,   956 ), /*   960 unpeer_crypto_    */
  S_ST( 'a',	3,      962,     0 ), /*   961 unpeer_crypto_n   */
  S_ST( 'k',	3,      963,     0 ), /*   962 unpeer_crypto_na  */
  S_ST( '_',	3,      964,     0 ), /*   963 unpeer_crypto_nak */
  S_ST( 'e',	3,      965,     0 ), /*   964 unpeer_crypto_nak_ */
  S_ST( 'a',	3,      966,     0 ), /*   965 unpeer_crypto_nak_e */
  S_ST( 'r',	3,      967,     0 ), /*   966 unpeer_crypto_nak_ea */
  S_ST( 'l',	3,      448,     0 ), /*   967 unpeer_crypto_nak_ear */
  S_ST( 'd',	3,      969,   949 ), /*   968 unpeer_           */
  S_ST( 'i',	3,      970,     0 ), /*   969 unpeer_d          */
  S_ST( 'g',	3,      971,     0 ), /*   970 unpeer_di         */
  S_ST( 'e',	3,      972,     0 ), /*   971 unpeer_dig        */
  S_ST( 's',	3,      973,     0 ), /*   972 unpeer_dige       */
  S_ST( 't',	3,      974,     0 ), /*   973 unpeer_diges      */
  S_ST( '_',	3,      975,     0 ), /*   974 unpeer_digest     */
  S_ST( 'e',	3,      976,     0 ), /*   975 unpeer_digest_    */
  S_ST( 'a',	3,      977,     0 ), /*   976 unpeer_digest_e   */
  S_ST( 'r',	3,      978,     0 ), /*   977 unpeer_digest_ea  */
  S_ST( 'l',	3,      449,     0 ), /*   978 unpeer_digest_ear */
  S_ST( 'v',	3,      980,   938 ), /*   979                   */
  S_ST( 'e',	3,      981,     0 ), /*   980 v                 */
  S_ST( 'r',	3,      982,     0 ), /*   981 ve                */
  S_ST( 's',	3,      983,     0 ), /*   982 ver               */
  S_ST( 'i',	3,      984,     0 ), /*   983 vers              */
  S_ST( 'o',	3,      452,     0 ), /*   984 versi             */
  S_ST( 'w',	3,      992,   979 ), /*   985                   */
  S_ST( 'a',	3,      987,     0 ), /*   986 w                 */
  S_ST( 'n',	3,      988,     0 ), /*   987 wa                */
  S_ST( 'd',	3,      989,     0 ), /*   988 wan               */
  S_ST( 'e',	3,      467,     0 ), /*   989 wand              */
  S_ST( 'e',	3,      991,   986 ), /*   990 w                 */
  S_ST( 'e',	3,      454,     0 ), /*   991 we                */
  S_ST( 'i',	3,      993,   990 ), /*   992 w                 */
  S_ST( 'l',	3,      994,     0 ), /*   993 wi                */
  S_ST( 'd',	3,      995,     0 ), /*   994 wil               */
  S_ST( 'c',	3,      996,     0 ), /*   995 wild              */
  S_ST( 'a',	3,      997,     0 ), /*   996 wildc             */
  S_ST( 'r',	3,      455,     0 ), /*   997 wildca            */
  S_ST( 'x',	3,     1003,   985 ), /*   998                   */
  S_ST( 'l',	3,     1000,     0 ), /*   999 x                 */
  S_ST( 'e',	3,     1001,     0 ), /*  1000 xl                */
  S_ST( 'a',	3,     1002,     0 ), /*  1001 xle               */
  S_ST( 'v',	3,      456,     0 ), /*  1002 xlea              */
  S_ST( 'm',	3,     1004,   999 ), /*  1003 x                 */
  S_ST( 't',	3,     1005,     0 ), /*  1004 xm                */
  S_ST( 'n',	3,     1006,     0 ), /*  1005 xmt               */
  S_ST( 'o',	3,     1007,     0 ), /*  1006 xmtn              */
  S_ST( 'n',	3,     1008,     0 ), /*  1007 xmtno             */
  S_ST( 'c',	3,      457,     0 ), /*  1008 xmtnon            */
  S_ST( 'y',	3,     1010,   998 ), /*  1009 [initial state]   */
  S_ST( 'e',	3,     1011,     0 ), /*  1010 y                 */
  S_ST( 'a',	3,      458,     0 )  /*  1011 ye                */
};

